f= open('fileops.txt','r')
print('name of the file', f.name)
print('mode of the file', f.mode)
print('is file readable?', f.readable())
print('is file writable?', f.writable())
f.close()
print('is file closed?', f.closed)