import time
print("Starting Attack on NASA......")
time.sleep(5)
print("Hacking NASA 0%")
time.sleep(5)
print("Hacking NASA 20%")
time.sleep(5)
print("Hacking NASA 40%")
time.sleep(5)
print("Hacking NASA 60%")
time.sleep(5)
print("Hacking NASA 80%")
time.sleep(5)
print("Hacked NASA Successfully")